"""add_service_categories

Revision ID: 7d9a7b100dba
Revises: 004
Create Date: 2026-01-04 13:27:08.119886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9a7b100dba'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('clients', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_schedule_exceptions_doctor_id', table_name='schedule_exceptions')
    op.drop_index('ix_service_products_service_id', table_name='service_products')
    op.drop_index('ix_service_steps_service_id', table_name='service_steps')
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'service_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    op.create_index('ix_service_steps_service_id', 'service_steps', ['service_id'], unique=False)
    op.create_index('ix_service_products_service_id', 'service_products', ['service_id'], unique=False)
    op.create_index('ix_schedule_exceptions_doctor_id', 'schedule_exceptions', ['doctor_id'], unique=False)
    op.alter_column('clients', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('service_categories')
    # ### end Alembic commands ###
